[[flavour]]
name = 'loong64'
[flavour.defs]
is_default = true
[flavour.description]
hardware = '64-bit LoongArch platforms'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
enable_vdso = true
kernel_file = 'arch/loongarch/boot/vmlinuz.efi'
kernel_stem = 'vmlinuz'
