[[flavour]]
name = 'alpha-generic'
[flavour.description]
hardware = 'Alpha'
hardware_long = 'DEC Alpha systems with extended kernel start address (Wildfire, Titan, Marvel)'
[flavour.packages]
installer = true

[[flavour]]
name = 'alpha-smp'
[flavour.defs]
is_default = true
[flavour.description]
hardware = 'Alpha SMP'
hardware_long = 'DEC Alpha SMP systems with extended kernel start address (Wildfire, Titan, Marvel)'

[[featureset]]
name = 'none'

[build]
kernel_file = 'arch/alpha/boot/vmlinux.gz'
kernel_stem = 'vmlinuz'

[relations.image]
suggests = [
  'aboot',
  'fdutils',
]
