#ifndef _SXEVF_PCI_H_
#define _SXEVF_PCI_H_

#define PCI_VENDOR_ID_STARS		 0x1FF2
#define SXEVF_DEV_ID_ASIC		 0x10a2
#define SXEVF_DEV_ID_ASIC_HV	 0x10a3

#define SXEVF_DMA_BIT_WIDTH_64	 64
#define SXEVF_DMA_BIT_WIDTH_32	 32

#define SXEVF_READ_CFG_WORD_FAILED   0xFFFFU

#endif

