[[flavour]]
name = 'sparc64'
[flavour.build]
config = [
  'kernelarch-sparc/config-up',
]
[flavour.description]
hardware = 'uniprocessor 64-bit UltraSPARC'
[flavour.packages]
installer = true

[[flavour]]
name = 'sparc64-smp'
[flavour.build]
config = [
  'kernelarch-sparc/config-smp',
]
[flavour.defs]
is_default = true
[flavour.description]
hardware = 'multiprocessor 64-bit UltraSPARC'

[[featureset]]
name = 'none'

[build]
kernel_file = 'vmlinux'
kernel_stem = 'vmlinux'

[relations.image]
suggests = [
  'fdutils',
  'grub-ieee1275',
]
