
mwv207-y := mwv207_drv.o \
	mwv207_irq.o \
	mwv207_db.o \
	mwv207_ctx.o \
	mwv207_submit.o \
	mwv207_sched.o \
	mwv207_pipe_codec_common.o \
	mwv207_devfreq.o \
	mwv207_pipe_2d.o \
	mwv207_pipe_3d.o \
	mwv207_pipe_dec.o \
	mwv207_pipe_enc.o \
	mwv207_pipe_dma.o \
	mwv207_gem.o \
	mwv207_bo.o \
	mwv207_ttm.o \
	mwv207_vcmd.o \
	mwv207_vbios.o \
	dc/mwv207_kms.o \
	dc/mwv207_va.o \
	dc/mwv207_edp.o \
	dc/mwv207_hdmi.o \
	dc/mwv207_vga.o \
	dc/mwv207_dvo.o \
	dc/mwv207_vi.o \
	dc/mwv207_i2c.o \
	selftest/selftest.o

obj-$(CONFIG_DRM_MWV207) := mwv207.o

ccflags-y := -I$(src)


