# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_IEE)	+= iee.o iee-gate.o iee-init.o iee-func.o iee-mmu.o
obj-$(CONFIG_IEE_SIP) += iee-si-gate.o iee-si.o
obj-$(CONFIG_IEE_PTRP) += iee-token.o
ccflags-y += -I$(srctree)/mm