dtb-$(CONFIG_ARCH_PHYTIUM) += pe2204-demo-ddr4.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2204-demo-ddr4-local.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2202-demo-ddr4.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2202-demo-ddr4-local.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2201-demo-ddr4.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pd2308-demo-a.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pd2308-demo-b.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += ps2316-devboard-16c-dsk.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pd2408-devboard-d4-dsk.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
