dtb-$(CONFIG_ARCH_PHYTIUM) += pe2204-demo-ddr4.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2204-demo-ddr4-local.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2202-demo-ddr4.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2202-demo-ddr4-local.dtb
dtb-$(CONFIG_ARCH_PHYTIUM) += pe2201-demo-ddr4.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
