# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

#obj-$(CONFIG_ARCH_PHYTIUM_EC)		+= ft-laptop.o
obj-$(CONFIG_ARCH_PHYTIUM_EC) += ft_laptop.o
obj-$(CONFIG_ARCH_PHYTIUM_EC) += ec_it8528.o
