[[flavour]]
name = '5kc-malta'
[flavour.build]
config = [
  'kernelarch-mips/config.malta',
  'kernelarch-mips/config.mips64r2',
]
[flavour.description]
hardware = 'MIPS Malta'
hardware_long = 'MIPS Malta boards'
[flavour.packages]
installer = true

[[flavour]]
name = 'mips64r2eb'
[flavour.build]
config = [
  'kernelarch-mips/config.boston',
  'kernelarch-mips/config.mips64r2',
]
[flavour.description]
hardware = 'MIPS Generic (mips64r2eb)'
hardware_long = 'MIPS Generic platform (mips64r2eb)'
[flavour.packages]
installer = true

[[flavour]]
name = 'octeon'
[flavour.build]
config = [
  'kernelarch-mips/config.octeon',
]
kernel_file = 'vmlinux'
kernel_stem = 'vmlinux'
[flavour.description]
hardware = 'Octeon'
hardware_long = 'Cavium Networks Octeon'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
kernel_file = 'vmlinuz'
kernel_stem = 'vmlinuz'
