/**************************************************************
* 版权所有 (C)2013-2015, 深圳市中兴通讯股份有限公司
* 文件名称 : dpp_tbl_stat.h
* 文件标识 :
* 内容摘要 :
* 其它说明 :
* 当前版本 :
* 作    者 :
* 完成日期 : 2014/01/27
* DEPARTMENT: ASIC_FPGA_R&D_Dept
* MANUAL_PERCENT: 100%

* 修改记录1:
* 修改日期:
* 版 本 号:
* 修 改 人:
* 修改内容:
***************************************************************/

#ifndef DPP_TBL_STAT_H
#define DPP_TBL_STAT_H

#include "zxic_common.h"
#include "dpp_type_api.h"

typedef enum
{
    DPP_STAT_ITEM_RX_TOTAL_BYTES                   = 0,
    DPP_STAT_ITEM_TX_TOTAL_BYTES                   = 1,
    DPP_STAT_ITEM_RX_UNICAST_PKTS                  = 2,
    DPP_STAT_ITEM_RX_MULTICAST_PKTS                = 3,
    DPP_STAT_ITEM_RX_BROADCAST_PKTS                = 4,
    DPP_STAT_ITEM_TX_UNICAST_PKTS                  = 5,
    DPP_STAT_ITEM_TX_MULTICAST_PKTS                = 6,
    DPP_STAT_ITEM_TX_BROADCAST_PKTS                = 7,
    DPP_STAT_ITEM_RX_UNDERSIZE_PKTS                = 8,
    DPP_STAT_ITEM_RX_64_OCTERS_PKTS                = 9,
    DPP_STAT_ITEM_RX_65_127_OCTERS_PKTS            = 10,
    DPP_STAT_ITEM_RX_128_255_OCTERS_PKTS           = 11,
    DPP_STAT_ITEM_RX_256_511_OCTERS_PKTS           = 12,
    DPP_STAT_ITEM_RX_512_1023_OCTERS_PKTS          = 13,
    DPP_STAT_ITEM_RX_1024_1522_OCTERS_PKTS         = 14,
    DPP_STAT_ITEM_RX_1023_9022_OCTERS_PKTS         = 15,
    DPP_STAT_ITEM_TX_64_OCTERS_PKTS                = 16,
    DPP_STAT_ITEM_TX_65_127_OCTERS_PKTS            = 17,
    DPP_STAT_ITEM_TX_128_255_OCTERS_PKTS           = 18,
    DPP_STAT_ITEM_TX_256_511_OCTERS_PKTS           = 19,
    DPP_STAT_ITEM_TX_512_1023_OCTERS_PKTS          = 20,
    DPP_STAT_ITEM_TX_1024_1522_OCTERS_PKTS         = 21,
    DPP_STAT_ITEM_TX_1523_9022_OCTERS_PKTS         = 22,
    DPP_STAT_ITEM_RX_NO_ERROR_BYTES                = 23,
    DPP_STAT_ITEM_RX_ERROR_UNDERSIZE_PKTS          = 24,
    DPP_STAT_ITEM_RX_ERROR_JABBER_PKTS             = 25,
    DPP_STAT_ITEM_RX_PF_MULTICAST_PKTS             = 26,
    DPP_STAT_ITEM_RX_VF_BROADCAST_PKTS             = 27,
    DPP_STAT_ITEM_RX_1588_PKTS                     = 28,
    DPP_STAT_ITEM_TX_1588_PKTS                     = 29,
    DPP_STAT_ITEM_1588_DROP_PKTS                   = 30,
    DPP_STAT_ITEM_1588_NP_DRS_ENCRYPT_PKTS         = 31,
    DPP_STAT_ITEM_1588_DRS_NP_ENCRYPT_PKTS         = 32,
    DPP_STAT_ITEM_SPOOF_DROP_PKTS                  = 33,
    DPP_STAT_ITEM_NP_RX_VPORT_STATE_DROP_STAT      = 34,
    DPP_STAT_ITEM_RDMA_TX_STAT                     = 37,
    DPP_STAT_ITEM_RDMA_RX_STAT                     = 38,
    DPP_STAT_ITEM_NIC_OUT_RATE_LIMIT_DROP_STAT     = 39,
    DPP_STAT_ITEM_NIC_IN_RATE_LIMIT_DROP_STAT      = 40,
    DPP_STAT_ITEM_TX_MTU_DROP_STAT                 = 41,
    DPP_STAT_ITEM_RX_MTU_DROP_STAT                 = 42,
    DPP_STAT_ITEM_MCODE_PPU_PKTS                   = 43,
    DPP_STAT_ITEM_NP_PORT_UNICAST_RX_STAT          = 44,
    DPP_STAT_ITEM_NP_PORT_UNICAST_TX_STAT          = 45,
    DPP_STAT_ITEM_NP_PORT_MULTICAST_RX_STAT        = 46,
    DPP_STAT_ITEM_NP_PORT_MULTICAST_TX_STAT        = 47,
    DPP_STAT_ITEM_NP_PORT_BROADCAST_RX_STAT        = 48,
    DPP_STAT_ITEM_NP_PORT_BROADCAST_TX_STAT        = 49,
    DPP_STAT_ITEM_FD_FLOW_STAT                     = 50,
    DPP_STAT_ITEM_HPCC_STAT                        = 51,
    DPP_STAT_ITEM_ASN_PHYPORT_RX_PKTS              = 52,
    DPP_STAT_ITEM_PSN_PHYPORT_TX_PKTS              = 53,
    DPP_STAT_ITEM_PSN_PHYPORT_RX_PKTS              = 54,
    DPP_STAT_ITEM_PSN_ACK_PHYPORT_TX_PKTS          = 55,
    DPP_STAT_ITEM_PSN_ACK_PHYPORT_RX_PKTS          = 56,
    DPP_STAT_ITEM_PSN_HEARTBEAT_TX_PKTS            = 57,
    DPP_STAT_ITEM_PSN_HEARTBEAT_RX_PKTS            = 58,
    DPP_STAT_ITEM_PSN_HEARTBEAT_ACK_TX_PKTS        = 59,
    DPP_STAT_ITEM_PSN_HEARTBEAT_ACK_RX_PKTS        = 60,
    DPP_STAT_ITEM_IDMA_PHYPORT_PRIO_STAT           = 61,
    DPP_STAT_ITEM_ODMA_PHYPORT_PRIO_STAT           = 62,
    DPP_STAT_ITEM_UPPER                            = 255
}DPP_STAT_ITEM_E;

typedef struct{
    ZXIC_UINT64 bytes;
    ZXIC_UINT64 pkts;
}DPP_STAT_CNT128_T;

typedef union dpp_stat_value_u
{
    DPP_STAT_CNT128_T stat_cnt_128;  
    ZXIC_UINT64       stat_cnt_64;
}DPP_STAT_VALUE_U;

#define DPP_STAT_MC_PACKET_RX_CNT_ERAM_BAADDR           ((ZXIC_UINT32)(0x1A))
#define DPP_STAT_MC_PACKET_RX_CNT_ERAM_DEPTH            ((ZXIC_UINT32)(40))

#define DPP_STAT_BC_PACKET_RX_CNT_ERAM_BAADDR           ((ZXIC_UINT32)(0x42))
#define DPP_STAT_BC_PACKET_RX_CNT_ERAM_DEPTH            ((ZXIC_UINT32)(40 * 1024))

#define DPP_STAT_1588_PACKET_RX_CNT_ERAM_BAADDR         ((ZXIC_UINT32)(0xA042))
#define DPP_STAT_1588_PACKET_RX_CNT_ERAM_DEPTH          ((ZXIC_UINT32)(0x800))

#define DPP_STAT_1588_PACKET_TX_CNT_ERAM_BAADDR         ((ZXIC_UINT32)(0xA842))
#define DPP_STAT_1588_PACKET_TX_CNT_ERAM_DEPTH          ((ZXIC_UINT32)(0x800))

#define DPP_STAT_1588_PACKET_DROP_CNT_ERAM_BAADDR       ((ZXIC_UINT32)(0xB042))
#define DPP_STAT_1588_PACKET_DROP_CNT_ERAM_DEPTH        ((ZXIC_UINT32)(0x800))

#define DPP_STAT_1588_ENC_PACKET_RX_CNT_ERAM_BAADDR     ((ZXIC_UINT32)(0xC042))
#define DPP_STAT_1588_ENC_PACKET_RX_CNT_ERAM_DEPTH      ((ZXIC_UINT32)(0x800))

#define DPP_STAT_1588_ENC_PACKET_TX_CNT_ERAM_BAADDR     ((ZXIC_UINT32)(0xB842))
#define DPP_STAT_1588_ENC_PACKET_TX_CNT_ERAM_DEPTH      ((ZXIC_UINT32)(0x800))

#define DPP_STAT_SPOOF_PACKET_DROP_CNT_ERAM_BAADDR      ((ZXIC_UINT32)(0xC842))
#define DPP_STAT_SPOOF_PACKET_DROP_CNT_ERAM_DEPTH       ((ZXIC_UINT32)(0x40))

#define DPP_STAT_PORT_RDMA_PACKET_TX_CNT_ERAM_BAADDR    ((ZXIC_UINT32)(0x6C81)) // 128bit
#define DPP_STAT_PORT_RDMA_PACKET_TX_CNT_ERAM_DEPTH     ((ZXIC_UINT32)(0x400))

#define DPP_STAT_PORT_RDMA_PACKET_RX_CNT_ERAM_BAADDR    ((ZXIC_UINT32)(0x7081)) // 128bit
#define DPP_STAT_PORT_RDMA_PACKET_RX_CNT_ERAM_DEPTH     ((ZXIC_UINT32)(0x400))

#define DPP_STAT_PLCR_PACKET_DROP_TX_CNT_ERAM_BAADDR    ((ZXIC_UINT32)(0x7481)) // 128bit
#define DPP_STAT_PLCR_PACKET_DROP_TX_CNT_ERAM_DEPTH     ((ZXIC_UINT32)(0x800))

#define DPP_STAT_PLCR_PACKET_DROP_RX_CNT_ERAM_BAADDR    ((ZXIC_UINT32)(0x7C81)) // 128bit
#define DPP_STAT_PLCR_PACKET_DROP_RX_CNT_ERAM_DEPTH     ((ZXIC_UINT32)(0x800))

#define DPP_STAT_MTU_PACKET_DROP_TX_CNT_ERAM_BAADDR     ((ZXIC_UINT32)(0x8481)) // 128bit
#define DPP_STAT_MTU_PACKET_DROP_TX_CNT_ERAM_DEPTH      ((ZXIC_UINT32)(0x500))

#define DPP_STAT_MTU_PACKET_DROP_RX_CNT_ERAM_BAADDR     ((ZXIC_UINT32)(0x8981)) // 128bit
#define DPP_STAT_MTU_PACKET_DROP_RX_CNT_ERAM_DEPTH      ((ZXIC_UINT32)(0x500))

#define DPP_STAT_MCODE_PACKET_CNT_ERAM_BAADDR           ((ZXIC_UINT32)(0x11D02)) // 64bit
#define DPP_STAT_MCODE_PACKET_CNT_ERAM_DEPTH            ((ZXIC_UINT32)(0x280))

#define DPP_STAT_PORT_UC_PACKET_RX_CNT_ERAM_BAADDR      ((ZXIC_UINT32)(0x8FC1)) // 128bit
#define DPP_STAT_PORT_UC_PACKET_RX_CNT_ERAM_DEPTH       ((ZXIC_UINT32)(0x500))

#define DPP_STAT_PORT_UC_PACKET_TX_CNT_ERAM_BAADDR      ((ZXIC_UINT32)(0x94C1)) // 128bit
#define DPP_STAT_PORT_UC_PACKET_TX_CNT_ERAM_DEPTH       ((ZXIC_UINT32)(0x500))

#define DPP_STAT_PORT_MC_PACKET_RX_CNT_ERAM_BAADDR      ((ZXIC_UINT32)(0x99C1)) // 128bit
#define DPP_STAT_PORT_MC_PACKET_RX_CNT_ERAM_DEPTH       ((ZXIC_UINT32)(0x500))

#define DPP_STAT_PORT_MC_PACKET_TX_CNT_ERAM_BAADDR      ((ZXIC_UINT32)(0x9EC1)) // 128bit
#define DPP_STAT_PORT_MC_PACKET_TX_CNT_ERAM_DEPTH       ((ZXIC_UINT32)(0x500))

#define DPP_STAT_PORT_BC_PACKET_RX_CNT_ERAM_BAADDR      ((ZXIC_UINT32)(0xA3C1)) // 128bit
#define DPP_STAT_PORT_BC_PACKET_RX_CNT_ERAM_DEPTH       ((ZXIC_UINT32)(0x500))

#define DPP_STAT_PORT_BC_PACKET_TX_CNT_ERAM_BAADDR      ((ZXIC_UINT32)(0xA8C1)) // 128bit
#define DPP_STAT_PORT_BC_PACKET_TX_CNT_ERAM_DEPTH       ((ZXIC_UINT32)(0x500))

#define DPP_STAT_FD_ACL_CNT_ERAM_BAADDR                 ((ZXIC_UINT32)(0xADC1)) // 128bit
#define DPP_STAT_FD_ACL_CNT_ERAM_DEPTH                  ((ZXIC_UINT32)(0x800))

#define DPP_STAT_ASN_PHYPORT_RX_CNT_ERAM_BAADDR         ((ZXIC_UINT32)(0x17382)) // 64bit
#define DPP_STAT_ASN_PHYPORT_RX_CNT_ERAM_DEPTH          ((ZXIC_UINT32)(10))

#define DPP_STAT_PSN_PHYPORT_TX_CNT_ERAM_BAADDR         ((ZXIC_UINT32)(0x1738C)) // 64bit
#define DPP_STAT_PSN_PHYPORT_TX_CNT_ERAM_DEPTH          ((ZXIC_UINT32)(10))

#define DPP_STAT_PSN_PHYPORT_RX_CNT_ERAM_BAADDR         ((ZXIC_UINT32)(0x17396)) // 64bit
#define DPP_STAT_PSN_PHYPORT_RX_CNT_ERAM_DEPTH          ((ZXIC_UINT32)(10))

#define DPP_STAT_PSN_ACK_PHYPORT_TX_CNT_ERAM_BAADDR     ((ZXIC_UINT32)(0x173A0)) // 64bit
#define DPP_STAT_PSN_ACK_PHYPORT_TX_CNT_ERAM_DEPTH      ((ZXIC_UINT32)(10))

#define DPP_STAT_PSN_ACK_PHYPORT_RX_CNT_ERAM_BAADDR     ((ZXIC_UINT32)(0x173AA)) // 64bit
#define DPP_STAT_PSN_ACK_PHYPORT_RX_CNT_ERAM_DEPTH      ((ZXIC_UINT32)(10))

#endif
