# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-y		+= lpc/
obj-y		+= clk/
obj-y		+= ras/
obj-y		+= scto/
obj-y		+= ec/
obj-y		+= uart/

obj-$(CONFIG_ARCH_PHYTIUM)		+= phytium_s3.o
