[[flavour]]
name = 'parisc'
[flavour.defs]
is_default = true
[flavour.description]
hardware = '32-bit PA-RISC'
hardware_long = 'HP PA-RISC 32-bit systems with max 4 GB RAM'
[flavour.packages]
installer = true

[[flavour]]
name = 'parisc64'
[flavour.build]
compiler_gnutype = 'hppa64-linux-gnu'
compiler_gnutype_compat = 'hppa-linux-gnu'
[flavour.description]
hardware = '64-bit PA-RISC'
hardware_long = 'HP PA-RISC 64-bit systems with support for more than 4 GB RAM'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
kernel_file = 'arch/parisc/boot/bzImage'
kernel_stem = 'vmlinuz'

[relations.image]
suggests = ['palo']
