[[flavour]]
name = 'sh7751r'
[flavour.description]
hardware = 'sh7751r'
hardware_long = 'Renesas SH7751R R2D plus board'
[flavour.packages]
installer = true

[[flavour]]
name = 'sh7785lcr'
[flavour.description]
hardware = 'sh7785lcr'
hardware_long = 'Renesas SH7785 reference board'
[flavour.packages]
installer = true
[flavour.relations.image]
recommends = ['u-boot-tools']

[[featureset]]
name = 'none'

[build]
kernel_file = 'arch/sh/boot/zImage'
kernel_stem = 'vmlinuz'
