[[flavour]]
name = 's390x'
[flavour.defs]
is_default = true
[flavour.description]
hardware = 'IBM zSeries'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
enable_vdso = true
kernel_file = 'arch/s390/boot/bzImage'
kernel_stem = 'vmlinuz'

[relations.image]
suggests = [
  's390-tools',
]
