[[flavour]]
name = '4kc-malta'
[flavour.build]
config = [
  'kernelarch-mips/config.malta',
  'kernelarch-mips/config.mips32r2',
]
[flavour.description]
hardware = 'MIPS Malta'
hardware_long = 'MIPS Malta boards'
[flavour.packages]
installer = true

[[flavour]]
name = 'mips32r2el'
[flavour.build]
config = [
  'kernelarch-mips/config.boston',
  'kernelarch-mips/config.mips32r2',
]
[flavour.description]
hardware = 'MIPS Generic (mips32r2el)'
hardware_long = 'MIPS Generic platform (mips32r2el)'
[flavour.packages]
installer = true

[[flavour]]
name = 'loongson-3'
[flavour.build]
config = [
  'kernelarch-mips/config.loongson-3',
]
[flavour.description]
hardware = 'Loongson 3A/3B'
hardware_long = 'Loongson 3A or 3B based systems (e.g. from Loongson or Lemote)'
[flavour.packages]
installer = true
[flavour.relations.image]
recommends = ['pmon-update']

[[flavour]]
name = 'octeon'
[flavour.build]
config = [
  'kernelarch-mips/config.octeon',
]
kernel_file = 'vmlinux'
kernel_stem = 'vmlinux'
[flavour.description]
hardware = 'Octeon'
hardware_long = 'Cavium Networks Octeon'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
kernel_file = 'vmlinuz'
kernel_stem = 'vmlinuz'
