[[flavour]]
name = 'mips64r6el'
[flavour.build]
config = [
  'kernelarch-mips/config.boston',
  'kernelarch-mips/config.mips64r6',
]
[flavour.description]
hardware = 'MIPS Generic (mips64r6el)'
hardware_long = 'MIPS Generic platform (mips64r6el)'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
kernel_file = 'vmlinuz'
kernel_stem = 'vmlinuz'
