# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the i2c bus drivers.
#

obj-$(CONFIG_I2C_V2_PLATFORM)  += i2c-phytium-v2-platform.o
i2c-phytium-v2-platform-objs := i2c-phyt-platform.o i2c-phyt-common.o i2c-phyt-master.o i2c-phyt-slave.o
