# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_USB_PHYTIUM_PCI_V2)	+= phytium-usb-pci-v2.o

obj-$(CONFIG_USB_PHYTIUM_V2)	+= phytium-usb-platform-v2.o

phytium-usb-pci-v2-y	:= core.o pci.o host.o gadget.o otg.o mem.o ring.o

phytium-usb-platform-v2-y	:= core.o platform.o host.o gadget.o otg.o mem.o ring.o
