[[flavour]]
name = 'powerpc64le'
[flavour.build]
config = [
  'kernelarch-powerpc/config-arch-64',
  'kernelarch-powerpc/config-arch-64-le',
]
[flavour.defs]
is_default = true
[flavour.description]
hardware = 'Little-endian 64-bit PowerPC'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
kernel_file = 'vmlinux'
kernel_stem = 'vmlinux'

[relations.image]
suggests = [
  'mkvmlinuz',
  'grub-ieee1275',
]
