# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2023 Motorcomm, Inc.


obj-$(CONFIG_YT6801) += yt6801.o

yt6801-objs := fuxi-gmac-common.o \
	fuxi-gmac-desc.o \
	fuxi-gmac-ethtool.o \
	fuxi-gmac-hw.o \
	fuxi-gmac-net.o \
	fuxi-gmac-pci.o \
	fuxi-gmac-phy.o \
	fuxi-efuse.o \
	fuxi-gmac-debugfs.o
