# SPDX-License-Identifier: GPL-2.0-only
################################################################################
#
# Copyright (c) 2023 Motorcomm, Inc.
# Motorcomm Confidential and Proprietary.
#
# This is Motorcomm NIC driver relevant files. Please don't copy, modify,
# distribute without commercial permission.
#
################################################################################

obj-$(CONFIG_YT6801) += yt6801.o

yt6801-objs := fuxi-gmac-common.o \
	fuxi-gmac-desc.o \
	fuxi-gmac-ethtool.o \
	fuxi-gmac-hw.o \
	fuxi-gmac-net.o \
	fuxi-gmac-pci.o \
	fuxi-gmac-phy.o \
	fuxi-efuse.o \
	fuxi-dbg.o \
	fuxi-gmac-debugfs.o
