/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2008 - 2023 Xel Technology. */

#ifndef _XLNID_REGISTER_H_
#define _XLNID_REGISTER_H_

/* =============== SKYLAKE registers =============== */
#define SKYLAKE_TOP_BASE            0x00000000
#define SKYLAKE_CRG_BASE            0x00100000
#define SKYLAKE_PCIE_INTF_BASE      0x00200000
#define SKYLAKE_RX_CTL_BASE         0x00300000
#define SKYLAKE_TX_CTL_BASE         0x00400000
#define SKYLAKE_MAC_BASE            0x00500000
#define SKYLAKE_SPI_INTF_BASE       0x00600000
#define SKYLAKE_I2C_INTF_BASE       0x00700000
#define SKYLAKE_MDIO_MASTER_BASE    0x00800000
#define SKYLAKE_PHY_CTL_BASE        0x00900000
#define SKYLAKE_LINKSEC_BASE        0x00A00000
#define SKYLAKE_NCSI_BASE           0x00B00000
#define SKYLAKE_SMBUS_BASE          0x00C00000

/* TOP_MPI Registers */
#define SKYLAKE_TOP_VERSION         (SKYLAKE_TOP_BASE + 0x00000)
#define SKYLAKE_PTSW_MODE           (SKYLAKE_TOP_BASE + 0x000c)
#define SKYLAKE_TXBUFFER_MTI        (SKYLAKE_TOP_BASE + 0x15c)
#define SKYLAKE_LEDCTL              (SKYLAKE_TOP_BASE + 0x00600)
#define SKYLAKE_TOP_MPI_LINK_MODE   (SKYLAKE_TOP_BASE + 0x00700)
#define SKYLAKE_TOP_MPI_LINK_SPEED  (SKYLAKE_TOP_BASE + 0x0071C)
#define SKYLAKE_PCS_LINK_STATUS     (SKYLAKE_TOP_BASE + 0x00A90)

/* CRG regeisters */
#define SKYLAKE_CRG_PLL_XGMAC_AUX_CFG   (SKYLAKE_CRG_BASE + 0x0004)
#define SKYLAKE_CRG_SYS_RST_N           (SKYLAKE_CRG_BASE + 0x0010)
#define SKYLAKE_CRG_SDS_MEM_REQ         (SKYLAKE_CRG_BASE + 0x001C)
#define SKYLAKE_CRG_SDS_LANE_SEL        (SKYLAKE_CRG_BASE + 0x0018)
#define SKYLAKE_CRG_SDS_MEM_DATA        (SKYLAKE_CRG_BASE + 0x0020)
#define SKYLAKE_CRG_SDS_MEM_ADDR        (SKYLAKE_CRG_BASE + 0x0024)
#define SKYLAKE_CRG_SDS_IRST_POR_N      (SKYLAKE_CRG_BASE + 0x0048)
#define SKYLAKE_CRG_SDS_IPD_MULTI_SYNTH_N       (SKYLAKE_CRG_BASE + 0x004C)
#define SKYLAKE_CRG_SDS_IRST_MULTI_HARD_SYNTH_N (SKYLAKE_CRG_BASE + 0x005C)
#define SKYLAKE_CRG_LANE_IRST_PIPE_RST_N        (SKYLAKE_CRG_BASE + 0x0064)
#define SKYLAKE_CRG_LANE_IRST_MULTI_HARD_TXRX_N (SKYLAKE_CRG_BASE + 0x0068)
#define SKYLAKE_CRG_LANE_IPD_MULTI_TX_N         (SKYLAKE_CRG_BASE + 0x006C)
#define SKYLAKE_CRG_LANE_IPD_MULTI_RX_N         (SKYLAKE_CRG_BASE + 0x0070)
#define SKYLAKE_CRG_GMAC_LINK_RST_N     (SKYLAKE_CRG_BASE + 0x0204)
#define SKYLAKE_CRG_XGMAC_LINK_RST_N    (SKYLAKE_CRG_BASE + 0x0208)
#define SKYLAKE_CRG_SGMII_LINK_RST_N    (SKYLAKE_CRG_BASE + 0x020C)

/* PCIE_INTF registers */
#define SKYLAKE_UL_RX_PKT_CNT           (SKYLAKE_PCIE_INTF_BASE + 0x20000)
#define SKYLAKE_ECO_RESET               (SKYLAKE_PCIE_INTF_BASE + 0x30000)
#define SKYLAKE_RX_PD_FIFO_STATUS       (SKYLAKE_PCIE_INTF_BASE + 0x20154)
#define SKYLAKE_PCIE_DMA_CHANNEL_BUSY   (SKYLAKE_PCIE_INTF_BASE + 0x20140)
#define SKYLAKE_PCIE_DWC_PLREG_CMD      (SKYLAKE_PCIE_INTF_BASE + 0x20200)
#define SKYLAKE_PCIE_DWC_PLREG_WDATA    (SKYLAKE_PCIE_INTF_BASE + 0x20204)

/* Interrupt Registers */
#define SKYLAKE_EICR            (SKYLAKE_PCIE_INTF_BASE + 0x00800)
#define SKYLAKE_EICS            (SKYLAKE_PCIE_INTF_BASE + 0x00808)
#define SKYLAKE_EIMS            (SKYLAKE_PCIE_INTF_BASE + 0x00880)
#define SKYLAKE_EIMC            (SKYLAKE_PCIE_INTF_BASE + 0x00888)
#define SKYLAKE_EIAC            (SKYLAKE_PCIE_INTF_BASE + 0x00810)
#define SKYLAKE_EIAM            (SKYLAKE_PCIE_INTF_BASE + 0x00890)
#define SKYLAKE_EICR_EX(_i)     (SKYLAKE_PCIE_INTF_BASE + 0x00A80 + (_i) * 4)
#define SKYLAKE_EICS_EX(_i)     (SKYLAKE_PCIE_INTF_BASE + 0x00A90 + (_i) * 4)
#define SKYLAKE_EIMS_EX(_i)     (SKYLAKE_PCIE_INTF_BASE + 0x00AA0 + (_i) * 4)
#define SKYLAKE_EIMC_EX(_i)     (SKYLAKE_PCIE_INTF_BASE + 0x00AB0 + (_i) * 4)
#define SKYLAKE_EIAC_EX(_i)     (SKYLAKE_PCIE_INTF_BASE + 0x00AC0 + (_i) * 4)
#define SKYLAKE_EIAM_EX(_i)     (SKYLAKE_PCIE_INTF_BASE + 0x00AD0 + (_i) * 4)
#define SKYLAKE_EITR(_i)        (((_i) <= 23) ? (SKYLAKE_PCIE_INTF_BASE + 0x00820 + ((_i) * 4)) : \
					(SKYLAKE_PCIE_INTF_BASE + 0x012300 + (((_i) - 24) * 4)))
#define SKYLAKE_IVAR(_i)        (SKYLAKE_PCIE_INTF_BASE + 0x00900 + ((_i) * 4)) /* 24 at 0x900-0x960 */
#define SKYLAKE_IVAR_MISC       (SKYLAKE_PCIE_INTF_BASE + 0x00A00) /* misc MSI-X interrupt causes */
#define SKYLAKE_GPIE            (SKYLAKE_PCIE_INTF_BASE + 0x00898)
#define SKYLAKE_TCPTIMER        (SKYLAKE_PCIE_INTF_BASE + 0x0004C)

/* Transmit DMA registers */
#define SKYLAKE_TDBAL(_i)       (SKYLAKE_PCIE_INTF_BASE + 0x06000 + ((_i) * 0x40)) /* 32 of them (0-31)*/
#define SKYLAKE_TDBAH(_i)       (SKYLAKE_PCIE_INTF_BASE + 0x06004 + ((_i) * 0x40))
#define SKYLAKE_TDLEN(_i)       (SKYLAKE_PCIE_INTF_BASE + 0x06008 + ((_i) * 0x40))
#define SKYLAKE_TDH(_i)         (SKYLAKE_PCIE_INTF_BASE + 0x06010 + ((_i) * 0x40))
#define SKYLAKE_TDT(_i)         (SKYLAKE_PCIE_INTF_BASE + 0x06018 + ((_i) * 0x40))
#define SKYLAKE_TXDCTL(_i)      (SKYLAKE_PCIE_INTF_BASE + 0x06028 + ((_i) * 0x40))
#define SKYLAKE_TDWBAL(_i)      (SKYLAKE_PCIE_INTF_BASE + 0x06038 + ((_i) * 0x40))
#define SKYLAKE_TDWBAH(_i)      (SKYLAKE_PCIE_INTF_BASE + 0x0603C + ((_i) * 0x40))

/* Receive DMA Registers */
#define SKYLAKE_RDBAL(_i)       (SKYLAKE_PCIE_INTF_BASE + 0x01000 + ((_i) * 0x40))
#define SKYLAKE_RDBAH(_i)       (SKYLAKE_PCIE_INTF_BASE + 0x01004 + ((_i) * 0x40))
#define SKYLAKE_RDLEN(_i)       (SKYLAKE_PCIE_INTF_BASE + 0x01008 + ((_i) * 0x40))
#define SKYLAKE_RDH(_i)         (SKYLAKE_PCIE_INTF_BASE + 0x01010 + ((_i) * 0x40))
#define SKYLAKE_SRRCTL(_i)      (SKYLAKE_PCIE_INTF_BASE + 0x01014 + ((_i) * 0x40))
#define SKYLAKE_RDT(_i)         (SKYLAKE_PCIE_INTF_BASE + 0x01018 + ((_i) * 0x40))
#define SKYLAKE_RXDCTL(_i)      (SKYLAKE_PCIE_INTF_BASE + 0x01028 + ((_i) * 0x40))
#define SKYLAKE_RDRXCTL         (SKYLAKE_PCIE_INTF_BASE + 0x02F00)
#define SKYLAKE_RXCTRL          (SKYLAKE_PCIE_INTF_BASE + 0x03000)

/* Receive Registers */
#define SKYLAKE_RXCSUM          (SKYLAKE_RX_CTL_BASE + 0x05000)
#define SKYLAKE_MAXFRS          (SKYLAKE_RX_CTL_BASE + 0x04268)
#define SKYLAKE_RXDCTL_VME      (SKYLAKE_RX_CTL_BASE + 0x1028)
#define SKYLAKE_RXBUF_MAP_SEL   (SKYLAKE_RX_CTL_BASE + 0xF170)
#define SKYLAKE_HLREG0          (SKYLAKE_RX_CTL_BASE + 0x04240)
#define SKYLAKE_HLREG1          (SKYLAKE_RX_CTL_BASE + 0x04244)

/* Multicast Table Array - 128 entries */
#define SKYLAKE_MTA(_i)         (SKYLAKE_RX_CTL_BASE + 0x05200 + ((_i) * 4))
#define SKYLAKE_RAL(_i)         (SKYLAKE_RX_CTL_BASE + 0x0A200 + ((_i) * 8))
#define SKYLAKE_RAH(_i)         (SKYLAKE_RX_CTL_BASE + 0x0A204 + ((_i) * 8))

/* array of 4096 1-bit vlan filters */
#define SKYLAKE_VFTA(_i)        (SKYLAKE_RX_CTL_BASE + 0x0A000 + ((_i) * 4))
#define SKYLAKE_FCTRL           (SKYLAKE_RX_CTL_BASE + 0x05080)
#define SKYLAKE_VLNCTRL         (SKYLAKE_RX_CTL_BASE + 0x05088)
#define SKYLAKE_MCSTCTRL        (SKYLAKE_RX_CTL_BASE + 0x05090)
#define SKYLAKE_MRQC            (SKYLAKE_RX_CTL_BASE + 0x0EC80)
#define SKYLAKE_SAQF(_i)        (SKYLAKE_RX_CTL_BASE + 0x0E000 + ((_i) * 4)) /* Source Address Queue Filter */
#define SKYLAKE_DAQF(_i)        (SKYLAKE_RX_CTL_BASE + 0x0E200 + ((_i) * 4)) /* Dest. Address Queue Filter */
#define SKYLAKE_SDPQF(_i)       (SKYLAKE_RX_CTL_BASE + 0x0E400 + ((_i) * 4)) /* Src Dest. Addr Queue Filter */
#define SKYLAKE_FTQF(_i)        (SKYLAKE_RX_CTL_BASE + 0x0E600 + ((_i) * 4)) /* Five Tuple Queue Filter */
#define SKYLAKE_ETQF(_i)        (SKYLAKE_RX_CTL_BASE + 0x05128 + ((_i) * 4)) /* EType Queue Filter */
#define SKYLAKE_ETQS(_i)        (SKYLAKE_RX_CTL_BASE + 0x0EC00 + ((_i) * 4)) /* EType Queue Select */
#define SKYLAKE_SYNQF           (SKYLAKE_RX_CTL_BASE + 0x0EC30) /* SYN Packet Queue Filter */
#define SKYLAKE_RQTC            (SKYLAKE_RX_CTL_BASE + 0x0EC70)
#define SKYLAKE_MTQC            (SKYLAKE_RX_CTL_BASE + 0x08120)

#define SKYLAKE_L34T_IMIR(_i)   (SKYLAKE_RX_CTL_BASE + 0x0E800 + ((_i) * 4)) /*128 of these (0-127)*/
#define SKYLAKE_RSSRK(_i)       (SKYLAKE_RX_CTL_BASE + 0x0EB80 + ((_i) * 4))  /* 10 of these (0-9) */
#define SKYLAKE_RETA(_i)        (SKYLAKE_RX_CTL_BASE + 0x0EB00 + ((_i) * 4))  /* 32 of these (0-31) */
#define SKYLAKE_IMIRVP          (SKYLAKE_RX_CTL_BASE + 0x0EC60)
#define SKYLAKE_LLITHRESH       (SKYLAKE_RX_CTL_BASE + 0x0EC90)

/* Flow Director registers */
#define SKYLAKE_FDIRCTRL        (SKYLAKE_RX_CTL_BASE + 0x0EE00)
#define SKYLAKE_FDIRHKEY        (SKYLAKE_RX_CTL_BASE + 0x0EE68)
#define SKYLAKE_FDIRSKEY        (SKYLAKE_RX_CTL_BASE + 0x0EE6C)
#define SKYLAKE_FDIRDIP4M       (SKYLAKE_RX_CTL_BASE + 0x0EE3C)
#define SKYLAKE_FDIRSIP4M       (SKYLAKE_RX_CTL_BASE + 0x0EE40)
#define SKYLAKE_FDIRTCPM        (SKYLAKE_RX_CTL_BASE + 0x0EE44)
#define SKYLAKE_FDIRUDPM        (SKYLAKE_RX_CTL_BASE + 0x0EE48)
#define SKYLAKE_FDIRSCTPM       (SKYLAKE_RX_CTL_BASE + 0x0EE78)
#define SKYLAKE_FDIRIP6M        (SKYLAKE_RX_CTL_BASE + 0x0EE74)
#define SKYLAKE_FDIRM           (SKYLAKE_RX_CTL_BASE + 0x0EE70)

/* Flow Director Stats registers */
#define SKYLAKE_FDIRFREE        (SKYLAKE_RX_CTL_BASE + 0x0EE38)
#define SKYLAKE_FDIRLEN         (SKYLAKE_RX_CTL_BASE + 0x0EE4C)
#define SKYLAKE_FDIRUSTAT       (SKYLAKE_RX_CTL_BASE + 0x0EE50)
#define SKYLAKE_FDIRFSTAT       (SKYLAKE_RX_CTL_BASE + 0x0EE54)
#define SKYLAKE_FDIRMATCH       (SKYLAKE_RX_CTL_BASE + 0x0EE58)
#define SKYLAKE_FDIRMISS        (SKYLAKE_RX_CTL_BASE + 0x0EE5C)

/* Flow Director Programming registers */
#define SKYLAKE_FDIRSIPv6(_i)   (SKYLAKE_RX_CTL_BASE + 0x0EE0C + ((_i) * 4)) /* 3 of these (0-2) */
#define SKYLAKE_FDIRIPSA        (SKYLAKE_RX_CTL_BASE + 0x0EE18)
#define SKYLAKE_FDIRIPDA        (SKYLAKE_RX_CTL_BASE + 0x0EE1C)
#define SKYLAKE_FDIRPORT        (SKYLAKE_RX_CTL_BASE + 0x0EE20)
#define SKYLAKE_FDIRVLAN        (SKYLAKE_RX_CTL_BASE + 0x0EE24)
#define SKYLAKE_FDIRHASH        (SKYLAKE_RX_CTL_BASE + 0x0EE28)
#define SKYLAKE_FDIRCMD         (SKYLAKE_RX_CTL_BASE + 0x0EE2C)

/* Management */
#define SKYLAKE_MAVTV(_i)       (SKYLAKE_RX_CTL_BASE + 0x05010 + ((_i) * 4)) /* 8 of these (0-7) */
#define SKYLAKE_MFUTP(_i)       (SKYLAKE_RX_CTL_BASE + 0x05030 + ((_i) * 4)) /* 8 of these (0-7) */
#define SKYLAKE_MANC            (SKYLAKE_RX_CTL_BASE + 0x05820)
#define SKYLAKE_MFVAL           (SKYLAKE_RX_CTL_BASE + 0x05824)
#define SKYLAKE_MANC2H          (SKYLAKE_RX_CTL_BASE + 0x05860)
#define SKYLAKE_MDEF(_i)        (SKYLAKE_RX_CTL_BASE + 0x05890 + ((_i) * 4)) /* 8 of these (0-7) */
#define SKYLAKE_MIPAF           (SKYLAKE_RX_CTL_BASE + 0x058B0)
#define SKYLAKE_MMAL(_i)        (SKYLAKE_RX_CTL_BASE + 0x05910 + ((_i) * 8)) /* 4 of these (0-3) */
#define SKYLAKE_MMAH(_i)        (SKYLAKE_RX_CTL_BASE + 0x05914 + ((_i) * 8)) /* 4 of these (0-3) */
#define SKYLAKE_FTFT            (SKYLAKE_RX_CTL_BASE + 0x09400) /* 0x9400-0x97FC */
#define SKYLAKE_METF(_i)        (SKYLAKE_RX_CTL_BASE + 0x05190 + ((_i) * 4)) /* 4 of these (0-3) */
#define SKYLAKE_MDEF_EXT(_i)    (SKYLAKE_RX_CTL_BASE + 0x05160 + ((_i) * 4)) /* 8 of these (0-7) */

#define SKYLAKE_DMATXCTL        (SKYLAKE_TX_CTL_BASE + 0x04A80)

/* MAC regeisters */
#define XLNID_MAC_LAN_UNIT          0x10000
#define SKYLAKE_MCI_CMD_DATA        (SKYLAKE_MAC_BASE + 0x0000)
#define SKYLAKE_MCI_WDATA_I         (SKYLAKE_MAC_BASE + 0x0004)
#define SKYLAKE_MCI_RDATA_O         (SKYLAKE_MAC_BASE + 0x0008)
#define SKYLAKE_XGMAC_LOOPBACK_CTRL (SKYLAKE_MAC_BASE + 0x0020)

/* SPI_INTF registers */
#define SKYLAKE_EEC             (SKYLAKE_SPI_INTF_BASE + 0x10010)
#define SKYLAKE_EERD            (SKYLAKE_SPI_INTF_BASE + 0x10014)
#define SKYLAKE_EEWR            (SKYLAKE_SPI_INTF_BASE + 0x10018)

/* I2C_INTF registers */
#define SKYLAKE_I2CCTL          (SKYLAKE_I2C_INTF_BASE + 0x00028)
#define SKYLAKE_I2CRD0          (SKYLAKE_I2C_INTF_BASE + 0x0002C)
#define SKYLAKE_I2CRD1          (SKYLAKE_I2C_INTF_BASE + 0x00038)
#define SKYLAKE_I2CWR0          (SKYLAKE_I2C_INTF_BASE + 0x00030)
#define SKYLAKE_I2CWR1          (SKYLAKE_I2C_INTF_BASE + 0x0003C)
#define SKYLAKE_I2CCONF         (SKYLAKE_I2C_INTF_BASE + 0x00034)

/* MDIO_MASTER registers */
#define SKYLAKE_MAS_TXBUS_DATA  (SKYLAKE_MDIO_MASTER_BASE + 0x00008)
#define SKYLAKE_MAS_TXBUS_CTL   (SKYLAKE_MDIO_MASTER_BASE + 0x0000C)
#define SKYLAKE_MAS_SEND_EN     (SKYLAKE_MDIO_MASTER_BASE + 0x00010)
#define SKYLAKE_MAS_RECV_DATA   (SKYLAKE_MDIO_MASTER_BASE + 0x00030)

/* PHY_CTL regeister */
#define SKYLAKE_PHY_PI_COFNIG   (SKYLAKE_PHY_CTL_BASE + 0x00)
#define SKYLAKE_PI_PHYADDR      (SKYLAKE_PHY_CTL_BASE + 0x08)
#define SKYLAKE_SGM_MAC_COFNIG  (SKYLAKE_PHY_CTL_BASE + 0x10)
#define SKYLAKE_SGM_AN_COFNIG   (SKYLAKE_PHY_CTL_BASE + 0x14)

#define SKYLAKE_FLUSH_REG       SKYLAKE_TOP_VERSION
/* =============== SKYLAKE registers =============== */


/* =============== WESTLAKE Registers =============== */
#define WESTLAKE_CRG_BASE           0x00000000
#define WESTLAKE_ETH_PORT_BASE      0x00100000
#define WESTLAKE_MACSEC_BASE        0x00200000
#define WESTLAKE_RX_CTL_BASE        0x00300000
#define WESTLAKE_TX_CTL_BASE        0x00400000
#define WESTLAKE_SMBUS_BASE         0x00500000
#define WESTLAKE_DMA_CTL_BASE       0x04e8
#define WESTLAKE_ETH_COMMON_BASE    0x00700000
#define WESTLAKE_MEM_CTL_BASE       0x00800000
#define WESTLAKE_PCIE_CTL_BASE      0x00900000
#define WESTLAKE_LED_BASE           0x00A00000
#define WESTLAKE_INNER_PHY_BASE     0x00B00000
#define WESTLAKE_USB_BASE           0x00C00000
#define WESTLAKE_OUTER_PHY_BASE     0x00D00000
#define WESTLAKE_DEBUG_BASE         0x00E00000
#define WESTLAKE_I2C_BASE           0x00F00000

/* CFG Registers */
#define WESTLAKE_TX_PTSW            0x0008
#define WESTLAKE_INDIRECT_CMD_BUS   0x0030
#define WESTLAKE_INDIRECT_WDATA_BUS 0x0034
#define WESTLAKE_INDIRECT_RDATA_BUS 0x0038

#define WESTLAKE_EICR               0x0280
#define WESTLAKE_EICS               0x0284
#define WESTLAKE_EIMS               0x0288
#define WESTLAKE_EIMC               0x028C
#define WESTLAKE_EIAM               0x0290
#define WESTLAKE_EIAC               0x0294
#define WESTLAKE_EICR_EX(_i)        (0x0298 + ((_i) * 0x4))
#define WESTLAKE_EICS_EX(_i)        (0x02A0 + ((_i) * 0x4))
#define WESTLAKE_EIMS_EX(_i)        (0x02A8 + ((_i) * 0x4))
#define WESTLAKE_EIMC_EX(_i)        (0x02B0 + ((_i) * 0x4))
#define WESTLAKE_EIAM_EX(_i)        (0x02B8 + ((_i) * 0x4))
#define WESTLAKE_EITR(_i)           (0x02C0 + ((_i) * 0x4))
#define WESTLAKE_IVAR(_i)           (0x03C0 + ((_i) * 0x4))
#define WESTLAKE_IVAR_MISC          0x04C0
#define WESTLAKE_GPIE               0x04C4
#define WESTLAKE_TCPTIMER           0x04C8

#define WESTLAKE_FLUSH_REG          0x0000

/* GMAC Registers */
#define WESTLAKE_GMAC_CONFIG        0x0000
#define WESTLAKE_GMAC_MPTC          0x0120
#define WESTLAKE_GMAC_PTC64         0x0124
#define WESTLAKE_GMAC_PTC127        0x0128
#define WESTLAKE_GMAC_PTC255        0x012c
#define WESTLAKE_GMAC_PTC511        0x0130
#define WESTLAKE_GMAC_PTC1023       0x0134
#define WESTLAKE_GMAC_PTC1522       0x0138
#define WESTLAKE_GMAC_BPTC          0x0144
#define WESTLAKE_GMAC_GOTC          0x0164
#define WESTLAKE_GMAC_GPTC          0x0168
#define WESTLAKE_GMAC_LXONTXC       0x0170
#define WESTLAKE_GMAC_TPR           0x0180
#define WESTLAKE_GMAC_GORC          0x0188
#define WESTLAKE_GMAC_BPRC          0x018C
#define WESTLAKE_GMAC_MPRC          0x0190
#define WESTLAKE_GMAC_CRCERRS       0x0194
#define WESTLAKE_GMAC_RUC           0x01A4
#define WESTLAKE_GMAC_ROC           0x01A8
#define WESTLAKE_GMAC_PRC64         0x01AC
#define WESTLAKE_GMAC_PRC127        0x01B0
#define WESTLAKE_GMAC_PRC255        0x01B4
#define WESTLAKE_GMAC_PRC511        0x01B8
#define WESTLAKE_GMAC_PRC1023       0x01BC
#define WESTLAKE_GMAC_PRC1522       0x01C0
#define WESTLAKE_GMAC_UPRC          0x01C4
#define WESTLAKE_GMAC_RLEC          0x01C8

#define WESTLAKE_MAC_CMD_WR              0x80000000
#define WESTLAKE_MAC_CMD_RD              0x00000000
#define WESTLAKE_MAC_RW_ADDR_MASK        0x00003FFF

/* CRG Registers */
#define WESTLAKE_CRG_STAT_PLL_FUSE_READY      (WESTLAKE_CRG_BASE + 0x0018)
#define WESTLAKE_CFG_ETH_PTP_CLK_SEL          (WESTLAKE_CRG_BASE + 0x001C)
#define WESTLAKE_CFG_PTSW_MODE                (WESTLAKE_CRG_BASE + 0x0020)
#define WESTLAKE_CRG_ETH_PORT_RST_N           (WESTLAKE_CRG_BASE + 0x00)

/* ETH_PORT Registers */
#define WESTLAKE_MAC_WDATA              (WESTLAKE_ETH_PORT_BASE + 0x0018)
#define WESTLAKE_MAC_CMD                (WESTLAKE_ETH_PORT_BASE + 0x001C)
#define WESTLAKE_MAC_RDATA              (WESTLAKE_ETH_PORT_BASE + 0x0020)
#define WESTLAKE_CFG_TXBUF_RD_TH        (WESTLAKE_ETH_PORT_BASE + 0x0034)
#define WESTLAKE_CFG_AN_EDIT_EN         (WESTLAKE_ETH_PORT_BASE + 0x00C4)
#define WESTLAKE_CFG_CHKSUM_EN          (WESTLAKE_ETH_PORT_BASE + 0x0210)
#define WESTLAKE_CFG_ETH_EN             (WESTLAKE_ETH_PORT_BASE + 0x0214)
#define WESTLAKE_CFG_CF_EN              (WESTLAKE_ETH_PORT_BASE + 0x0220)
#define WESTLAKE_CFG_RX_MSGTYPE_CHK_EN  (WESTLAKE_ETH_PORT_BASE + 0x022c)
#define WESTLAKE_CFG_RX_SNAPTS_RDEN     (WESTLAKE_ETH_PORT_BASE + 0x0238)
#define WESTLAKE_CFG_TX_MSGTYPE_CHK_EN  (WESTLAKE_ETH_PORT_BASE + 0x024c)
#define WESTLAKE_CFG_TS_UPT_EN          (WESTLAKE_ETH_PORT_BASE + 0x0248)
#define WESTLAKE_CFG_TX_SNAPTS_RDEN     (WESTLAKE_ETH_PORT_BASE + 0x025c)
#define WESTLAKE_RPT_RX_SNAP_TS0        (WESTLAKE_ETH_PORT_BASE + 0x0260)
#define WESTLAKE_RPT_RX_SNAP_TS1        (WESTLAKE_ETH_PORT_BASE + 0x0264)
#define WESTLAKE_RPT_RX_SNAP_TS2        (WESTLAKE_ETH_PORT_BASE + 0x0268)
#define WESTLAKE_RPT_TX_SNAP_TS0        (WESTLAKE_ETH_PORT_BASE + 0x0274)
#define WESTLAKE_RPT_TX_SNAP_TS1        (WESTLAKE_ETH_PORT_BASE + 0x0278)
#define WESTLAKE_RPT_TX_SNAP_TS2        (WESTLAKE_ETH_PORT_BASE + 0x027c)
#define WESTLAKE_CFG_TS_UPLOAD_EN       (WESTLAKE_ETH_PORT_BASE + 0x029c)
#define WESTLAKE_SNAP_TS_RDY            (WESTLAKE_ETH_PORT_BASE + 0x02a0)
#define WESTLAKE_SGM_PCS_CFG0           (WESTLAKE_ETH_PORT_BASE + 0x0400)
#define WESTLAKE_SGM_PCS_STAS0          (WESTLAKE_ETH_PORT_BASE + 0x0404)
#define WESTLAKE_SGM_PCS_CFG1           (WESTLAKE_ETH_PORT_BASE + 0x0408)
#define WESTLAKE_SGM_PCS_STAS1          (WESTLAKE_ETH_PORT_BASE + 0x040C)
#define WESTLAKE_SDS_IRST_IPD_CTRL      (WESTLAKE_ETH_PORT_BASE + 0x048C)
#define WESTLAKE_SDS_PMA_REF_CTRL       (WESTLAKE_ETH_PORT_BASE + 0x0494)
#define WESTLAKE_SDS_TX_EQ              (WESTLAKE_ETH_PORT_BASE + 0x04A0)
#define WESTLAKE_SDS_TXDEEMPH           (WESTLAKE_ETH_PORT_BASE + 0x04A4)
#define WESTLAKE_SDS_RX_EQ0             (WESTLAKE_ETH_PORT_BASE + 0x04A8)
#define WESTLAKE_SDS_RX_EQ1             (WESTLAKE_ETH_PORT_BASE + 0x04AC)
#define WESTLAKE_SDS_RX_EQ2             (WESTLAKE_ETH_PORT_BASE + 0x04B0)
#define WESTLAKE_SDS_OCTL_STATUS0       (WESTLAKE_ETH_PORT_BASE + 0x04B4)
#define WESTLAKE_GEPHY_LED_STATUS       (WESTLAKE_ETH_PORT_BASE + 0x0514)
#define WESTLAKE_CFG_P1588_BYPASS       (WESTLAKE_ETH_PORT_BASE + 0x0580)
#define WESTLAKE_CFG_SPEED              (WESTLAKE_ETH_PORT_BASE + 0x058C)
#define WESTLAKE_CFG_LINK_UP            (WESTLAKE_ETH_PORT_BASE + 0x0590)
#define WESTLAKE_CFG_AN_EN              (WESTLAKE_ETH_PORT_BASE + 0x059C)
#define WESTLAKE_CFG_EXT_POLL           (WESTLAKE_ETH_PORT_BASE + 0x05A0)
#define WESTLAKE_CFG_INTF_CTRL          (WESTLAKE_ETH_PORT_BASE + 0x05A4)
#define WESTLAKE_CFG_LINK_MASK          (WESTLAKE_ETH_PORT_BASE + 0x05A8)
#define WESTALEK_CFG_AN_EN              (WESTLAKE_ETH_PORT_BASE + 0x059C)
#define WESTLAKE_CFG_TXBUF_AFULL_TH     (WESTLAKE_ETH_PORT_BASE + 0x0030)
#define WESTLAKE_TXBUF_RD_TH            (WESTLAKE_ETH_PORT_BASE + 0x0034)
#define WESTLKAE_CFG_PAUSE_PERIOD       (WESTLAKE_ETH_PORT_BASE + 0x0048)
#define WESTLAKE_CFG_FC_EN              (WESTLAKE_ETH_PORT_BASE + 0x002C)
#define WESTLAKE_CFG_RX_PAUSE_EN        (WESTLAKE_ETH_PORT_BASE + 0x004c)
#define WESTLAKE_PI_CONFG0              (WESTLAKE_ETH_PORT_BASE + 0x0500)
#define WESTLAKE_PI_CFG1                (WESTLAKE_ETH_PORT_BASE + 0x0520)
#define WESTLAKE_PI_CFG2                (WESTLAKE_ETH_PORT_BASE + 0x0524)

/* ETH_COMMON_BASE Registers */
#define WESTLAKE_CFG_PPS_CTRL       (WESTLAKE_ETH_COMMON_BASE + 0x0020)
#define WESTLAKE_CFG_PPS_WID        (WESTLAKE_ETH_COMMON_BASE + 0x0024)
#define WESTLAKE_CFG_UPDT_VID       (WESTLAKE_ETH_COMMON_BASE + 0x0034)
#define WESTLAKE_CFG_INIT_VID       (WESTLAKE_ETH_COMMON_BASE + 0x0038)
#define WESTLAKE_RPT_CURR_TS1       (WESTLAKE_ETH_COMMON_BASE + 0x0040)
#define WESTLAKE_RPT_CURR_TS2       (WESTLAKE_ETH_COMMON_BASE + 0x0044)
#define WESTLAKE_RPT_CURR_TS3       (WESTLAKE_ETH_COMMON_BASE + 0x0048)
#define WESTLAKE_CFG_UPDR_TS0       (WESTLAKE_ETH_COMMON_BASE + 0x004C)
#define WESTLAKE_CFG_UPDR_TS1       (WESTLAKE_ETH_COMMON_BASE + 0x0050)
#define WESTLAKE_ADD_SUB_FLAG       (WESTLAKE_ETH_COMMON_BASE + 0x0078)
#define WESTLAKE_UPDATE_TYPE        (WESTLAKE_ETH_COMMON_BASE + 0x007C)
#define WESTLAKE_RPT_CURR_TS0       (WESTLAKE_ETH_COMMON_BASE + 0x003C)

/* MACSEC Registers */
#define WESTLAKE_MACSEC_RX_CTL              (WESTLAKE_MACSEC_BASE + 0x0004)
#define WESTLAKE_MACSEC_RX_SCL              (WESTLAKE_MACSEC_BASE + 0x0008)
#define WESTLAKE_MACSEC_RX_SCH              (WESTLAKE_MACSEC_BASE + 0x000c)
#define WESTLAKE_MACSEC_RX_SA0              (WESTLAKE_MACSEC_BASE + 0x0010)
#define WESTLAKE_MACSEC_RX_SA1              (WESTLAKE_MACSEC_BASE + 0x0014)

#define WESTLAKE_MACSEC_RX_PN0              (WESTLAKE_MACSEC_BASE + 0x0018)
#define WESTLAKE_MACSEC_RX_PN1              (WESTLAKE_MACSEC_BASE + 0x001C)

#define WESTLAKE_MACSEC_RX_KEY0_0           (WESTLAKE_MACSEC_BASE + 0x0020)
#define WESTLAKE_MACSEC_RX_KEY0_1           (WESTLAKE_MACSEC_BASE + 0x0024)
#define WESTLAKE_MACSEC_RX_KEY0_2           (WESTLAKE_MACSEC_BASE + 0x0028)
#define WESTLAKE_MACSEC_RX_KEY0_3           (WESTLAKE_MACSEC_BASE + 0x002C)
#define WESTLAKE_MACSEC_RX_KEY1_0           (WESTLAKE_MACSEC_BASE + 0x0030)
#define WESTLAKE_MACSEC_RX_KEY1_1           (WESTLAKE_MACSEC_BASE + 0x0034)
#define WESTLAKE_MACSEC_RX_KEY1_2           (WESTLAKE_MACSEC_BASE + 0x0038)
#define WESTLAKE_MACSEC_RX_KEY1_3           (WESTLAKE_MACSEC_BASE + 0x003C)

#define WESTLAKE_MACSEC_RX_UT               (WESTLAKE_MACSEC_BASE + 0x0040)
#define WESTLAKE_MACSEC_RX_OCTE             (WESTLAKE_MACSEC_BASE + 0x0044)
#define WESTLAKE_MACSEC_RX_OCTP             (WESTLAKE_MACSEC_BASE + 0x0048)
#define WESTLAKE_MACSEC_RX_BAD              (WESTLAKE_MACSEC_BASE + 0x004C)
#define WESTLAKE_MACSEC_RX_NOSCI            (WESTLAKE_MACSEC_BASE + 0x0050)
#define WESTLAKE_MACSEC_RX_UNSCI            (WESTLAKE_MACSEC_BASE + 0x0054)
#define WESTLAKE_MACSEC_RX_UC               (WESTLAKE_MACSEC_BASE + 0x0058)
#define WESTLAKE_MACSEC_RX_DELAY            (WESTLAKE_MACSEC_BASE + 0x005C)
#define WESTLAKE_MACSEC_RX_LATE             (WESTLAKE_MACSEC_BASE + 0x0060)
#define WESTLAKE_MACSEC_RX_OK0              (WESTLAKE_MACSEC_BASE + 0x0064)
#define WESTLAKE_MACSEC_RX_OK1              (WESTLAKE_MACSEC_BASE + 0x0068)
#define WESTLAKE_MACSEC_RX_INV0             (WESTLAKE_MACSEC_BASE + 0x006C)
#define WESTLAKE_MACSEC_RX_INV1             (WESTLAKE_MACSEC_BASE + 0x0070)
#define WESTLAKE_MACSEC_RX_NV0              (WESTLAKE_MACSEC_BASE + 0x0074)
#define WESTLAKE_MACSEC_RX_NV1              (WESTLAKE_MACSEC_BASE + 0x0078)
#define WESTLAKE_MACSEC_RX_UNSA             (WESTLAKE_MACSEC_BASE + 0x007C)
#define WESTLAKE_MACSEC_RX_NUSA             (WESTLAKE_MACSEC_BASE + 0x0080)

#define WESTLAKE_MACSEC_TX_CTL              (WESTLAKE_MACSEC_BASE + 0x008C)
#define WESTLAKE_MACSEC_TX_SCL              (WESTLAKE_MACSEC_BASE + 0x0090)
#define WESTLAKE_MACSEC_TX_SCH              (WESTLAKE_MACSEC_BASE + 0x0094)
#define WESTLAKE_MACSEC_TX_SA               (WESTLAKE_MACSEC_BASE + 0x0098)
#define WESTLAKE_MACSEC_TX_PN0              (WESTLAKE_MACSEC_BASE + 0x009C)
#define WESTLAKE_MACSEC_TX_PN1              (WESTLAKE_MACSEC_BASE + 0x00A0)

#define WESTLAKE_MACSEC_TX_KEY0_0           (WESTLAKE_MACSEC_BASE + 0x00A4)
#define WESTLAKE_MACSEC_TX_KEY0_1           (WESTLAKE_MACSEC_BASE + 0x00A8)
#define WESTLAKE_MACSEC_TX_KEY0_2           (WESTLAKE_MACSEC_BASE + 0x00AC)
#define WESTLAKE_MACSEC_TX_KEY0_3           (WESTLAKE_MACSEC_BASE + 0x00B0)
#define WESTLAKE_MACSEC_TX_KEY1_0           (WESTLAKE_MACSEC_BASE + 0x00B4)
#define WESTLAKE_MACSEC_TX_KEY1_1           (WESTLAKE_MACSEC_BASE + 0x00B8)
#define WESTLAKE_MACSEC_TX_KEY1_2           (WESTLAKE_MACSEC_BASE + 0x00BC)
#define WESTLAKE_MACSEC_TX_KEY1_3           (WESTLAKE_MACSEC_BASE + 0x00C0)

#define WESTLAKE_MACSEC_TX_UT               (WESTLAKE_MACSEC_BASE + 0x00C4)
#define WESTLAKE_MACSEC_TX_PKTE             (WESTLAKE_MACSEC_BASE + 0x00C8)
#define WESTLAKE_MACSEC_TX_PKTP             (WESTLAKE_MACSEC_BASE + 0x00CC)
#define WESTLAKE_MACSEC_TX_OCTE             (WESTLAKE_MACSEC_BASE + 0x00D0)
#define WESTLAKE_MACSEC_TX_OCTP             (WESTLAKE_MACSEC_BASE + 0x00D4)

#define WESTLAKE_MACSEC_RX_SOP_CNT          (WESTLAKE_MACSEC_BASE + 0x0104)
#define WESTLAKE_MACSEC_ETH_LOOPBACK_CFG    (WESTLAKE_MACSEC_BASE + 0x0138)
#define WESTLAKE_MACSEC_RX_DEAL_INTERVAL    (WESTLAKE_MACSEC_BASE + 0x013C)

/* RX_CTL Registers */
#define WESTLAKE_FDIRCTRL           (WESTLAKE_RX_CTL_BASE + 0x0000)
#define WESTLAKE_FDIRHKEY           (WESTLAKE_RX_CTL_BASE + 0x0004)
#define WESTLAKE_FDIRDIP4M          (WESTLAKE_RX_CTL_BASE + 0x0008)
#define WESTLAKE_FDIRSIP4M          (WESTLAKE_RX_CTL_BASE + 0x000C)
#define WESTLAKE_FDIRTCPM           (WESTLAKE_RX_CTL_BASE + 0x0010)
#define WESTLAKE_FDIRUDPM           (WESTLAKE_RX_CTL_BASE + 0x0014)
#define WESTLAKE_FDIRIPV6M          (WESTLAKE_RX_CTL_BASE + 0x0018)
#define WESTLAKE_FDIRM              (WESTLAKE_RX_CTL_BASE + 0x001C)
#define WESTLAKE_FDIRFREE           (WESTLAKE_RX_CTL_BASE + 0x0020)
#define WESTLAKE_FDIRUSTAT          (WESTLAKE_RX_CTL_BASE + 0x0024)
#define WESTLAKE_FDIRFSTAT          (WESTLAKE_RX_CTL_BASE + 0x0028)
#define WESTLAKE_FDIRMATCH          (WESTLAKE_RX_CTL_BASE + 0x002C)
#define WESTLAKE_FDIRMISS           (WESTLAKE_RX_CTL_BASE + 0x0030)
#define WESTLAKE_FDISIPv6(_i)       (WESTLAKE_RX_CTL_BASE + 0x0034 + ((_i) * 0x4))
#define WESTLAKE_FDIRIPSA           (WESTLAKE_RX_CTL_BASE + 0x0040)
#define WESTLAKE_FDIRIPDA           (WESTLAKE_RX_CTL_BASE + 0x0044)
#define WESTLAKE_FDIRPORT           (WESTLAKE_RX_CTL_BASE + 0x0048)
#define WESTLAKE_FDIRVLAN           (WESTLAKE_RX_CTL_BASE + 0x004C)
#define WESTLAKE_FDIRHASH           (WESTLAKE_RX_CTL_BASE + 0x0050)
#define WESTLAKE_FDIRCMD            (WESTLAKE_RX_CTL_BASE + 0x0054)
#define WESTLAKE_FDIRIP6AT(_i)      (WESTLAKE_RX_CTL_BASE + 0x0058 + ((_i) * 0x4))
#define WESTLAKE_HLREG0             (WESTLAKE_RX_CTL_BASE + 0x0070)
#define WESTLAKE_FCTRL              (WESTLAKE_RX_CTL_BASE + 0x0074)
#define WESTLAKE_VLNCTRL            (WESTLAKE_RX_CTL_BASE + 0x0078)
#define WESTLAKE_MCSTCTRL           (WESTLAKE_RX_CTL_BASE + 0x007C)
#define WESTLAKE_RXCSUM             (WESTLAKE_RX_CTL_BASE + 0x0080)
#define WESTLAKE_MRQC               (WESTLAKE_RX_CTL_BASE + 0x0084)
#define WESTLAKE_SYNQF              (WESTLAKE_RX_CTL_BASE + 0x0088)
#define WESTLAKE_RSSRK(_i)          (WESTLAKE_RX_CTL_BASE + 0x0090 + ((_i) * 0x4))
#define WESTLAKE_ETQF(_i)           (WESTLAKE_RX_CTL_BASE + 0x00C0 + ((_i) * 0x4))
#define WESTLAKE_ETQS(_i)           (WESTLAKE_RX_CTL_BASE + 0x00E0 + ((_i) * 0x4))
#define WESTLAKE_LLITHRESH          (WESTLAKE_RX_CTL_BASE + 0x0100)
#define WESTLAKE_IMIRVP             (WESTLAKE_RX_CTL_BASE + 0x0104)
#define WESTLAKE_MAXFRS             (WESTLAKE_RX_CTL_BASE + 0x0108)
#define WESTLAKE_RXDCTL_VME         (WESTLAKE_RX_CTL_BASE + 0x010C)
#define WESTLAKE_MANC               (WESTLAKE_RX_CTL_BASE + 0x0110)
#define WESTLAKE_MFVAL              (WESTLAKE_RX_CTL_BASE + 0x0114)
#define WESTLAKE_MANC2H             (WESTLAKE_RX_CTL_BASE + 0x0118)
#define WESTLAKE_RXCTRL             (WESTLAKE_RX_CTL_BASE + 0x011C)
#define WESTLAKE_RX_DROP_EN_MASK    (WESTLAKE_RX_CTL_BASE + 0x012C)
#define WESTLAKE_MTA(_i)            (WESTLAKE_RX_CTL_BASE + 0x0200 + ((_i) * 0x4))
#define WESTLAKE_VFTA(_i)           (WESTLAKE_RX_CTL_BASE + 0x0400 + ((_i) * 0x4))
#define WESTLAKE_RETA(_i)           (WESTLAKE_RX_CTL_BASE + 0x0600 + ((_i) * 0x4))
#define WESTLAKE_RAL(_i)            (WESTLAKE_RX_CTL_BASE + 0x0800 + ((_i) * 0x8))
#define WESTLAKE_RAH(_i)            (WESTLAKE_RX_CTL_BASE + 0x0804 + ((_i) * 0x8))
#define WESTLAKE_SAQF(_i)           (WESTLAKE_RX_CTL_BASE + 0x0C00 + ((_i) * 0x4))
#define WESTLAKE_DAQF(_i)           (WESTLAKE_RX_CTL_BASE + 0x0E00 + ((_i) * 0x4))
#define WESTLAKE_SDPQF(_i)          (WESTLAKE_RX_CTL_BASE + 0x1000 + ((_i) * 0x4))
#define WESTLAKE_FTQF(_i)           (WESTLAKE_RX_CTL_BASE + 0x1200 + ((_i) * 0x4))
#define WESTLAKE_L34T_IMIR(_i)      (WESTLAKE_RX_CTL_BASE + 0x1400 + ((_i) * 0x4))
#define WESTLAKE_MAVTV(_i)          (WESTLAKE_RX_CTL_BASE + 0x1600 + ((_i) * 0x4))
#define WESTLAKE_MFUTP(_i)          (WESTLAKE_RX_CTL_BASE + 0x1620 + ((_i) * 0x4))
#define WESTLAKE_METF(_i)           (WESTLAKE_RX_CTL_BASE + 0x1640 + ((_i) * 0x4))
#define WESTLAKE_MDEF(_i)           (WESTLAKE_RX_CTL_BASE + 0x1650 + ((_i) * 0x4))
#define WESTLAKE_MDEF_EXT(_i)       (WESTLAKE_RX_CTL_BASE + 0x1670 + ((_i) * 0x4))
#define WESTLAKE_RX_PBUF_STAT       (WESTLAKE_RX_CTL_BASE + 0x3024)
#define WESTLAKE_RX_PBUF_ALF_POINT  (WESTLAKE_RX_CTL_BASE + 0x3004)
#define WESTLAKE_RX_PDBUF_ALF_POINT (WESTLAKE_RX_CTL_BASE + 0x3008)
#define WESTLAKE_RX_BP_MASK         (WESTLAKE_RX_CTL_BASE + 0x0124)


/* TX_CTL Registers */
#define WESTLAKE_DMATXCTL           (WESTLAKE_TX_CTL_BASE + 0x0000)

/* SMBUS Registers */

/* DMA_CTL Registers */
#define WESTLAKE_TX_PKTREQ_FIFO_TH      (WESTLAKE_DMA_CTL_BASE + 0x0050)
#define WESTLAKE_TX_DESC_USED_FIFO_TH   (WESTLAKE_DMA_CTL_BASE + 0x005c)
#define WESTLAKE_DMA_FIFO_STATUS        (WESTLAKE_DMA_CTL_BASE + 0x0088)
#define WESTLAKE_RDBAL(_i)          (WESTLAKE_DMA_CTL_BASE + 0x0120 + ((_i) * 0x40))
#define WESTLAKE_RDBAH(_i)          (WESTLAKE_DMA_CTL_BASE + 0x0124 + ((_i) * 0x40))
#define WESTLAKE_RDLEN(_i)          (WESTLAKE_DMA_CTL_BASE + 0x0128 + ((_i) * 0x40))
#define WESTLAKE_RDH(_i)            (WESTLAKE_DMA_CTL_BASE + 0x012C + ((_i) * 0x40))
#define WESTLAKE_RDT(_i)            (WESTLAKE_DMA_CTL_BASE + 0x0130 + ((_i) * 0x40))
#define WESTLAKE_RXDCTL(_i)         (WESTLAKE_DMA_CTL_BASE + 0x0134 + ((_i) * 0x40))
#define WESTLAKE_SRRCTL(_i)         (WESTLAKE_DMA_CTL_BASE + 0x0138 + ((_i) * 0x40))
#define WESTLAKE_TDBAL(_i)          (WESTLAKE_DMA_CTL_BASE + 0x013C + ((_i) * 0x40))
#define WESTLAKE_TDBAH(_i)          (WESTLAKE_DMA_CTL_BASE + 0x0140 + ((_i) * 0x40))
#define WESTLAKE_TDLEN(_i)          (WESTLAKE_DMA_CTL_BASE + 0x0144 + ((_i) * 0x40))
#define WESTLAKE_TDH(_i)            (WESTLAKE_DMA_CTL_BASE + 0x0148 + ((_i) * 0x40))
#define WESTLAKE_TDT(_i)            (WESTLAKE_DMA_CTL_BASE + 0x014C + ((_i) * 0x40))
#define WESTLAKE_TXDCTL(_i)         (WESTLAKE_DMA_CTL_BASE + 0x0150 + ((_i) * 0x40))

/* LED Registers */
#define WESTLAKE_LEDCTL             (WESTLAKE_LED_BASE + 0x0000)
#define WESTLAKE_LEDCTL_1           (WESTLAKE_LED_BASE + 0x0004)
#define WESTLAKE_LED_BLINK_TIMERL   (WESTLAKE_LED_BASE + 0x0018)
#define WESTLAKE_LED_BLINK_TIMERH   (WESTLAKE_LED_BASE + 0x001C)
#define WESTLAKE_LEDMODE            (WESTLAKE_LED_BASE + 0x0020)
#define WESTLAKE_LEDCMD             (WESTLAKE_CRG_BASE + 0x0040)

/* INNER_PHY/OUTER_PHY Registers */
#define WESTLAKE_MDIO_WDATA         0x0008
#define WESTLAKE_MDIO_CTL           0x000C
#define WESTLAKE_MDIO_EN            0x0010
#define WESTLAKE_MDIO_RDATA         0x0030
#define WESTLAKE_MDIO_BUSY          0x0034

/* DEBUG Registers */
#define WESTLAKE_DEBUG_PHYSTATUS      (WESTLAKE_DEBUG_BASE + 0x001C)
#define WESTLAKE_DEBUG_INT_STATUS1    (WESTLAKE_DEBUG_BASE + 0x000C)

/* I2C Registers */
#define WESTLAKE_I2C_SLAVE_ADDR     (WESTLAKE_I2C_BASE + 0x0004)
#define WESTLAKE_I2C_WORD_ADDR      (WESTLAKE_I2C_BASE + 0x0008)
#define WESTLAKE_I2C_WDATA          (WESTLAKE_I2C_BASE + 0x000C)
#define WESTLAKE_I2C_RDATA          (WESTLAKE_I2C_BASE + 0x0024)
#define WESTLAKE_I2C_MST_EN         (WESTLAKE_I2C_BASE + 0x0044)

#define I2C_WR_MODE_4B              (0x3 << 26)
#define I2C_RD_MODE_4B              (0x3 << 24)
#define I2C_WR_MODE_2B              (0x1 << 26)
#define I2C_RD_MODE_2B              (0x1 << 24)
#define I2C_WR_MODE_1B              (0x0 << 26)
#define I2C_RD_MODE_1B              (0x0 << 24)

#define I2C_CMD_WR                  (0x1 << 16)
#define I2C_CMD_RD                  (0x2 << 16)
#define I2C_SLAVE_ADDR_MASK         (0x00007FFF)
#define I2C_SLAVE_ADDR              0x50
#define I2C_WORD_ADDR_MASK          (0x0000FFFF)
#define WESTLAKE_EEPROM_START_ENTRY0 0X15
#define WESTLAKE_EEPROM_START_ENTRY1 0X2a

/* SPI Registers */
#define WESTLAKE_SPI_CTRLR0         (WESTLAKE_I2C_BASE + 0x0000)
#define WESTLAKE_SPI_CTRLR1         (WESTLAKE_I2C_BASE + 0x0004)
#define WESTLAKE_SPI_SSIENR         (WESTLAKE_I2C_BASE + 0x0008)
#define WESTLAKE_SPI_MWCR           (WESTLAKE_I2C_BASE + 0x000C)
#define WESTLAKE_SPI_SER            (WESTLAKE_I2C_BASE + 0x0010)
#define WESTLAKE_SPI_BAUDR          (WESTLAKE_I2C_BASE + 0x0014)
#define WESTLAKE_SPI_TXFTLR         (WESTLAKE_I2C_BASE + 0x0018)
#define WESTLAKE_SPI_RXFTLR         (WESTLAKE_I2C_BASE + 0x001C)
#define WESTLAKE_SPI_TXFLR          (WESTLAKE_I2C_BASE + 0x0020)
#define WESTLAKE_SPI_RXFLR          (WESTLAKE_I2C_BASE + 0x0024)
#define WESTLAKE_SPI_DRX(_i)        (WESTLAKE_I2C_BASE + 0x0060 + ((_i) * 0x4))

#define SPI_DISABLE_DWC_SSI         0
#define SPI_EABLE_DWC_SSI           1
#define SPI_CTRLR0_READ             0x0c07
#define SPI_CTRLR0_WRITE            0x0407
#define SPI_BAUDR_SCKDV             0x007c
/* =============== WESTLAKE Registers =============== */


/* =============== LK10 & LK40 Registers =============== */
#define LK10_CFG_BASE           0x00000000
#define LK10_CRG_BASE           0x00010000
#define LK10_ETH_BASE           0x00020000
#define LK10_MACADP_BASE        0x00030000
#define LK10_RXCTL_BASE         0x00040000
#define LK10_TXCTL_BASE         0x00050000
#define LK10_DMACTL_BASE        0x00060000
#define LK10_I2C_BASE           0x00070000
#define LK10_PCIE_BASE          0x00080000
#define LK10_LED_BASE           0x00090000
#define LK10_INTN_BASE          0x000A0000

#define LK10_XGMAC_RXMTU        0x414
#define LK10_XGMAC_TXMTU        0x418
#define LK10_XGMAC_RXCONFIG     0x404

#define LK10_ETH_LINKUP         (LK10_ETH_BASE + 0x0000)
#define LK10_XGMAC_AWADDR       (LK10_ETH_BASE + 0x0030)
#define LK10_XGMAC_WDATA        (LK10_ETH_BASE + 0x0034)
#define LK10_XGMAC_WSTARTUP     (LK10_ETH_BASE + 0x0038)
#define LK10_XGMAC_ARADDR       (LK10_ETH_BASE + 0x0040)
#define LK10_XGMAC_RDATA        (LK10_ETH_BASE + 0x0044)
#define LK10_XGMAC_RSTARTUP     (LK10_ETH_BASE + 0x0048)
#define LK10_RDT(_i)            (LK10_DMACTL_BASE + 0x0130 + ((_i) * 0x40))
#define LK10_TDT(_i)            (LK10_DMACTL_BASE + 0x014C + ((_i) * 0x40))

#define XLNID_XGMAC_ADDRMASK    (0x00000FFF)
/* =============== LK10 & LK40 Registers =============== */


/* =============== Lodestar Registers =============== */
#define LODESTAR_DMACTL_BASE    0x00001000
#define LODESTAR_PCIE_BASE      0x00005000

#define LODESTAR_RDBAL(_i)      (LODESTAR_DMACTL_BASE + 0x120 + ((_i) * 0x40))
#define LODESTAR_RDBAH(_i)      (LODESTAR_DMACTL_BASE + 0x124 + ((_i) * 0x40))
#define LODESTAR_RDLEN(_i)      (LODESTAR_DMACTL_BASE + 0x128 + ((_i) * 0x40))
#define LODESTAR_RDH(_i)        (LODESTAR_DMACTL_BASE + 0x12c + ((_i) * 0x40))
#define LODESTAR_RDT(_i)        (LODESTAR_DMACTL_BASE + 0x130 + ((_i) * 0x40))
#define LODESTAR_RXDCTL(_i)     (LODESTAR_DMACTL_BASE + 0x134 + ((_i) * 0x40))
#define LODESTAR_SRRCTL(_i)     (LODESTAR_DMACTL_BASE + 0x138 + ((_i) * 0x40))
#define LODESTAR_TDBAL(_i)      (LODESTAR_DMACTL_BASE + 0x13c + ((_i) * 0x40))
#define LODESTAR_TDBAH(_i)      (LODESTAR_DMACTL_BASE + 0x140 + ((_i) * 0x40))
#define LODESTAR_TDLEN(_i)      (LODESTAR_DMACTL_BASE + 0x144 + ((_i) * 0x40))
#define LODESTAR_TDH(_i)        (LODESTAR_DMACTL_BASE + 0x148 + ((_i) * 0x40))
#define LODESTAR_TDT(_i)        (LODESTAR_DMACTL_BASE + 0x14c + ((_i) * 0x40))
#define LODESTAR_TXDCTL(_i)     (LODESTAR_DMACTL_BASE + 0x150 + ((_i) * 0x40))

#define LODESTAR_EICR           (LODESTAR_PCIE_BASE + 0x480)
#define LODESTAR_EICS           (LODESTAR_PCIE_BASE + 0x484)
#define LODESTAR_EIMS           (LODESTAR_PCIE_BASE + 0x488)
#define LODESTAR_EIMC           (LODESTAR_PCIE_BASE + 0x48c)
#define LODESTAR_EIAM           (LODESTAR_PCIE_BASE + 0x490)
#define LODESTAR_EIAC           (LODESTAR_PCIE_BASE + 0x494)
#define LODESTAR_EICR_EX(_i)    (LODESTAR_PCIE_BASE + 0x498 + ((_i) * 0x4))
#define LODESTAR_EICS_EX(_i)    (LODESTAR_PCIE_BASE + 0x4a0 + ((_i) * 0x4))
#define LODESTAR_EIMS_EX(_i)    (LODESTAR_PCIE_BASE + 0x4a8 + ((_i) * 0x4))
#define LODESTAR_EIMC_EX(_i)    (LODESTAR_PCIE_BASE + 0x4b0 + ((_i) * 0x4))
#define LODESTAR_EIAM_EX(_i)    (LODESTAR_PCIE_BASE + 0x4b8 + ((_i) * 0x4))
#define LODESTAR_EITR(_i)       (LODESTAR_PCIE_BASE + 0x4c0 + ((_i) * 0x4))
#define LODESTAR_IVAR(_i)       (LODESTAR_PCIE_BASE + 0x5c0 + ((_i) * 0x4))
#define LODESTAR_IVAR_MISC      (LODESTAR_PCIE_BASE + 0x6c0)
#define LODESTAR_GPIE           (LODESTAR_PCIE_BASE + 0x6c4)
/* =============== Lodestar Registers =============== */


#endif /* _XLNID_REGISTER_H_ */


