[[kernelarch]]
name = 'alpha'
  [[kernelarch.debianarch]]
  name = 'alpha'

[[kernelarch]]
name = 'arm'
  [[kernelarch.debianarch]]
  name = 'armel'
  [[kernelarch.debianarch]]
  name = 'armhf'

[[kernelarch]]
name = 'arm64'
  [[kernelarch.debianarch]]
  name = 'arm64'

[[kernelarch]]
name = 'parisc'
  [[kernelarch.debianarch]]
  name = 'hppa'

[[kernelarch]]
name = 'loongarch'
  [[kernelarch.debianarch]]
  name = 'loong64'

[[kernelarch]]
name = 'm68k'
  [[kernelarch.debianarch]]
  name = 'm68k'

[[kernelarch]]
name = 'mips'
  [[kernelarch.debianarch]]
  name = 'mips'
  [[kernelarch.debianarch]]
  name = 'mips64'
  [[kernelarch.debianarch]]
  name = 'mips64el'
  [[kernelarch.debianarch]]
  name = 'mips64r6el'
  [[kernelarch.debianarch]]
  name = 'mipsel'

[[kernelarch]]
name = 'powerpc'
  [[kernelarch.debianarch]]
  name = 'powerpc'
  [[kernelarch.debianarch]]
  name = 'ppc64'
  [[kernelarch.debianarch]]
  name = 'ppc64el'

[[kernelarch]]
name = 'riscv'
  [[kernelarch.debianarch]]
  name = 'riscv64'

[[kernelarch]]
name = 's390'
  [[kernelarch.debianarch]]
  name = 's390x'

[[kernelarch]]
name = 'sh'
  [[kernelarch.debianarch]]
  name = 'sh4'

[[kernelarch]]
name = 'sparc'
  [[kernelarch.debianarch]]
  name = 'sparc64'

[[kernelarch]]
name = 'x86'
  [[kernelarch.debianarch]]
  name = 'amd64'
  [[kernelarch.debianarch]]
  name = 'i386'
  [[kernelarch.debianarch]]
  name = 'x32'

[[featureset]]
name = 'none'

[[featureset]]
name = 'rt'
enable = true
  [featureset.description]
  parts = ['rt']
  [featureset.description.long]
  rt = 'This kernel includes the PREEMPT_RT realtime patch set.'
  [featureset.description.short]
  rt = 'PREEMPT_RT'

[build]
compiler = 'gcc-13'

[relations.image]
depends = [
  'initramfs-tools (>= 0.120+deb8u2) | linux-initramfs-tool',
]
recommends = [
  'apparmor',
]
breaks = [
  'fwupdate (<< 12-7)',
  'wireless-regdb (<< 2019.06.03-1~)',
]
