# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SOPHGO) += mango-sophgo-x4evb.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += mango-sophgo-x8evb.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += mango-sophgo-pisces.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += mango-sophgo-capricorn.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += mango-milkv-pioneer.dtb
dtb-$(CONFIG_ARCH_SOPHGO) += mango-yixin-s2110.dtb
