[[flavour]]
name = 'm68k'
[flavour.defs]
is_default = true
[flavour.description]
hardware = 'Motorola MC68020+ family'
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
kernel_file = 'vmlinux'
kernel_stem = 'vmlinux'

[relations.image]
suggests = ['vmelilo', 'fdutils']
