[[flavour]]
name = 'rpi'
[flavour.description]
hardware = 'Raspberry Pi Zero, Zero W and 1'
hardware_long = 'Raspberry Pi Zero, Zero W and 1 based systems'

[[featureset]]
name = 'none'

[build]
kernel_file = 'arch/arm/boot/zImage'
kernel_stem = 'vmlinuz'
