# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 2022 - 2025 Phytium Technology Co., Ltd.
#
# Makefile for the Phytium PCI virtual network device drivers.

obj-$(CONFIG_PHYTIUM_PCI_EPF_VNET) += pci-ep-net/
