name: code check cap
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  cap:
    runs-on: ubuntu-latest
    outputs:
      reviewer: ${{ steps.cap-output.outputs.reviewer }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: code check cap
        id: cap-output
        run: |
          set -x
          echo "code checking cap"
          mkdir ../diff
          git show > ../diff/diff
          cd ../diff/
          cap_num=$(grep -En "\\s*[s|g]etcap\\s*" diff | wc -l || true)
          if [ "$cap_num"X != "0X" ];then
            echo "found cap changes, need review"
            echo "reviewer=CapReviewer" >> $GITHUB_OUTPUT
          else
            echo "reviewer=AUTO" >> $GITHUB_OUTPUT
          fi

  cap-review:
    needs: cap
    runs-on: ubuntu-latest
    environment: ${{ needs.cap-output.outputs.reviewer }}
    steps:
      - name: Handle cap review status
        #TODO: Use the github project to count the review results of the cap?
        run: |
          echo "cap changes reviewed by ${{ needs.cap-output.outputs.reviewer }}."