name: package kernel amd64 daily
on:
  schedule:
    - cron: "0 2 * * *"

env:
  KBUILD_BUILD_USER: deepin-kernel-sig
  KBUILD_BUILD_HOST: deepin-kernel-builder
  email: support@deepin.org

permissions:
  pull-requests: read

jobs:
  build-kernel:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: "Install Deps"
        run: |
          git config --global user.email $email
          git config --global user.name $KBUILD_BUILD_USER

      - name: "Compile kernel"
        run: |
          # .config
          make deepin_x86_desktop_defconfig
          make bindeb-pkg -j$(nproc)
          mv ../*.deb .

      - name: 'Upload Kernel Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: kernel-amd64-deb
          path: "*.deb"
